# helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
# helm install -n monitoring prometheus -f values.yaml prometheus-community/prometheus

# https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml
alertmanager:
  enabled: false

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: false

prometheus-pushgateway:
  enabled: false
