services:
  app:
    container_name: app
    build:
      context: app
    ports:
      - "5000:5000"
    networks:
      - monitoring
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - "./configs/prometheus.yml:/etc/prometheus/prometheus.yml"
      - ./prometheus-data:/prometheus
    networks:
      - monitoring
    ports:
      - 9090:9090
    

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - 9100:9100
    
networks:
  monitoring:
    name: monitoring-local

volumes:
  prometheus-data:
    driver: local
