services:
  app:
    container_name: app
    build:
      context: app
    ports:
      - "5000:5000"
    networks:
      - monitoring
  
  prometheus:
    image: prom/prometheus
    volumes:
      - "./configs/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - monitoring
    ports:
      - 9090:9090

networks:
  monitoring:
    name: monitoring-local
