services:
  app:
    container_name: goapp
    build:
      context: app
    ports:
      - "5000:5000"
    networks:
      - monitoring
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - "./configs/prometheus.yml:/etc/prometheus/prometheus.yml"
      - ./prometheus-data:/prometheus
    networks:
      - monitoring
    ports:
      - "9090:9090"

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - "9100:9100"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring
    ports:
     - "3100:3000"

networks:
  monitoring:
    name: monitoring-local

volumes:
  prometheus-data:
  grafana-data:
