global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  # Expose node-exporter
  # - job_name: node
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  # Expose goapp
  # - job_name: goapp
  #   static_configs:
  #     - targets: ['goapp:5000']
